### ISSUE TITLE
Installation failed, node-tmp

### ISSUE THREAD

**Issue by V1nzi** [MattFlower/organized#1]
When I try to install this package via atom, I always get following error:

Updating to “organized@0.4.0” failed.Hide output…

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\username\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\username\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\username\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\username\\.atom\\.apmrc" "install" "C:\\Users\\username\\AppData\\Local\\Temp\\d-11681-16820-bp9g5y\\package.tgz" "--target=0.37.8" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/node-tmp
npm ERR! 404 
npm ERR! 404 'node-tmp' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'organized'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

When I download the package manually and change the dependency in the package.json from "node-tmp" to just "tmp", it works.

**Comment by MattFlower** [comment]
Thanks for reporting the problem, doing everything in dev mode, I hadn't noticed it!  

It should be fine now in 0.4.2.
