### ISSUE TITLE
Deprecated selector in `organized/styles/organized.less`

### ISSUE THREAD

**Issue by thari** [MattFlower/organized#11]
In `organized/styles/organized.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .organized .header.level1.symbol,
atom-text-editor::shadow .organized .header.level1.symbol,
atom-text-editor .organized .header.level1.line,
atom-text-editor::shadow .organized .header.level1.line` => `atom-text-editor .organized .header.level1.symbol,
atom-text-editor.editor .syntax--organized .syntax--header.syntax--level1.syntax--symbol,
atom-text-editor .organized .header.level1.line,
atom-text-editor.editor .syntax--organized .syntax--header.syntax--level1.line`

* `atom-text-editor .organized .header.level2.symbol,
atom-text-editor::shadow .organized .header.level2.symbol,
atom-text-editor .organized .header.level2.line,
atom-text-editor::shadow .organized .header.level2.line` => `atom-text-editor .organized .header.level2.symbol,
atom-text-editor.editor .syntax--organized .syntax--header.syntax--level2.syntax--symbol,
atom-text-editor .organized .header.level2.line,
atom-text-editor.editor .syntax--organized .syntax--header.syntax--level2.line`

* `atom-text-editor .organized .header.level3.symbol,
atom-text-editor::shadow .organized .header.level3.symbol,
atom-text-editor .organized .header.level3.line,
atom-text-editor::shadow .organized .header.level3.line` => `atom-text-editor .organized .header.level3.symbol,
atom-text-editor.editor .syntax--organized .syntax--header.syntax--level3.syntax--symbol,
atom-text-editor .organized .header.level3.line,
atom-text-editor.editor .syntax--organized .syntax--header.syntax--level3.line`

* `atom-text-editor .organized .starline .star .level1,
atom-text-editor::shadow .organized .starline .star .level1` => `atom-text-editor .organized .starline .star .level1,
atom-text-editor.editor .syntax--organized .syntax--starline .syntax--star .syntax--level1`

* `atom-text-editor .organized .starline .todo,
atom-text-editor::shadow .organized .starline .todo` => `atom-text-editor .organized .starline .todo,
atom-text-editor.editor .syntax--organized .syntax--starline .syntax--todo`

* `atom-text-editor .organized .starline .completed,
atom-text-editor::shadow .organized .starline .completed` => `atom-text-editor .organized .starline .completed,
atom-text-editor.editor .syntax--organized .syntax--starline .syntax--completed`

* `atom-text-editor .organized .starline .tags,
atom-text-editor::shadow .organized .starline .tags` => `atom-text-editor .organized .starline .tags,
atom-text-editor.editor .syntax--organized .syntax--starline .syntax--tags`

* `atom-text-editor .organized .othertext.organized .scheduled .tag,
atom-text-editor::shadow .organized .othertext.organized .scheduled .tag` => `atom-text-editor .organized .othertext.organized .scheduled .tag,
atom-text-editor.editor .syntax--organized .othertext.syntax--organized .syntax--scheduled .syntax--tag`

* `atom-text-editor .organized .othertext.organized .scheduled .begintimeblock,
atom-text-editor::shadow .organized .othertext.organized .scheduled .begintimeblock` => `atom-text-editor .organized .othertext.organized .scheduled .begintimeblock,
atom-text-editor.editor .syntax--organized .othertext.syntax--organized .syntax--scheduled .syntax--begintimeblock`

* `atom-text-editor .organized .othertext.organized .scheduled .timeblock,
atom-text-editor::shadow .organized .othertext.organized .scheduled .timeblock` => `atom-text-editor .organized .othertext.organized .scheduled .timeblock,
atom-text-editor.editor .syntax--organized .othertext.syntax--organized .syntax--scheduled .syntax--timeblock`

* `atom-text-editor .organized .othertext.organized .scheduled .endtimeblock,
atom-text-editor::shadow .organized .othertext.organized .scheduled .endtimeblock` => `atom-text-editor .organized .othertext.organized .scheduled .endtimeblock,
atom-text-editor.editor .syntax--organized .othertext.syntax--organized .syntax--scheduled .syntax--endtimeblock`

* `atom-text-editor .organized .othertext.organized .code.block.tag.completed,
atom-text-editor::shadow .organized .othertext.organized .code.block.tag.completed` => `atom-text-editor .organized .othertext.organized .code.block.tag.completed,
atom-text-editor.editor .syntax--organized .othertext.syntax--organized .syntax--code.syntax--block.syntax--tag.syntax--completed`

* `atom-text-editor .organized .othertext.organized .code.block.language.completed,
atom-text-editor::shadow .organized .othertext.organized .code.block.language.completed` => `atom-text-editor .organized .othertext.organized .code.block.language.completed,
atom-text-editor.editor .syntax--organized .othertext.syntax--organized .syntax--code.syntax--block.syntax--language.syntax--completed`

* `atom-text-editor .organized .link.organized .link.brackets.organized,
atom-text-editor::shadow .organized .link.organized .link.brackets.organized,
atom-text-editor .organized .link.organized .link.parens.organized,
atom-text-editor::shadow .organized .link.organized .link.parens.organized` => `atom-text-editor .organized .link.organized .link.brackets.organized,
atom-text-editor.editor .syntax--organized .syntax--link.syntax--organized .syntax--link.syntax--brackets.syntax--organized,
atom-text-editor .organized .link.organized .link.parens.organized,
atom-text-editor.editor .syntax--organized .syntax--link.syntax--organized .syntax--link.syntax--parens.syntax--organized`

* `atom-text-editor .organized .link.organized .link.url.organized,
atom-text-editor::shadow .organized .link.organized .link.url.organized` => `atom-text-editor .organized .link.organized .link.url.organized,
atom-text-editor.editor .syntax--organized .syntax--link.syntax--organized .syntax--link.syntax--url.syntax--organized`

* `atom-text-editor .organized .link.organized .link.title.organized,
atom-text-editor::shadow .organized .link.organized .link.title.organized` => `atom-text-editor .organized .link.organized .link.title.organized,
atom-text-editor.editor .syntax--organized .syntax--link.syntax--organized .syntax--link.syntax--title.syntax--organized`

* `atom-text-editor .organized .bold.underlined.text.organized,
atom-text-editor::shadow .organized .bold.underlined.text.organized` => `atom-text-editor .organized .bold.underlined.text.organized,
atom-text-editor.editor .syntax--organized .syntax--bold.syntax--underlined.syntax--text.syntax--organized`

* `atom-text-editor .organized .underlined.text.organized,
atom-text-editor::shadow .organized .underlined.text.organized` => `atom-text-editor .organized .underlined.text.organized,
atom-text-editor.editor .syntax--organized .syntax--underlined.syntax--text.syntax--organized`

* `atom-text-editor .organized .bold.text.organized,
atom-text-editor::shadow .organized .bold.text.organized` => `atom-text-editor .organized .bold.text.organized,
atom-text-editor.editor .syntax--organized .syntax--bold.syntax--text.syntax--organized`

* `atom-text-editor .organized .border.table.organized,
atom-text-editor::shadow .organized .border.table.organized` => `atom-text-editor .organized .border.table.organized,
atom-text-editor.editor .syntax--organized .syntax--border.syntax--table.syntax--organized`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by MattFlower** [comment]
Good to go with 0.5.7.  Closing.
