### ISSUE TITLE
How to add other search directories and file types for [TODO] items? 

### ISSUE THREAD

**Issue by leonqli** [MattFlower/organized#13]
Thanks for the great work!

**Comment by MattFlower** [comment]
Hi Leon, you're very welcome.

The search directory field is comma-delimited.  So you could add:

/home/leon/notes,/home/leon/other_notes

And it should pick up both of them.

**Comment by leonqli** [comment]
Thanks, Matt! Is it possible to add markdown files? 
BTW, there is another good task plugin in Zim-wiki for your reference. 
Best, Leon

**Comment by MattFlower** [comment]
Thanks Leon,

I'll take a look at Zim-wiki.  It does seem to cater to a similar audience.

As far as adding markdown files, what do you mean exactly?  Are you talking about importing them, supporting the things you can do with the organized plugin inside of markdown, or something else?
