### ISSUE TITLE
Create TODO feature not working

### ISSUE THREAD

**Issue by Bigotacon** [MattFlower/organized#16]
I am on windows 7 and when I press ctrl-shift+t no TODO tags are created. I used the toolbar to toggle the TODO as well and that does not work as well.

**Comment by MattFlower** [comment]
Currently todo tags are only created when you are in an outline bullet - that is a paragraph beginning with a *, -, number with a period, etc.  Does that describe what you're doing?  If not, I'm interested in how a todo would work. Would the text of it be the current line or sentence?

**Comment by Bigotacon** [comment]
After using a * it works. Sorry about that I am dumb.  I cant seem to get the TODOs to be displayed in the sidebar. 
![image](https://cloud.githubusercontent.com/assets/20931755/25260261/a514f874-2610-11e7-9242-c5d8b161a3c3.png)

I do have enable Toolbar support and tool-bar installed.
