### ISSUE TITLE
TODO tags without brackets not shown in sidebar

### ISSUE THREAD

**Issue by phtrivier** [MattFlower/organized#17]
Its seems like a TODO created like this is not displayed in the Sidebar:

```
* TODO Save the cheerleader
```

This works: 

```
* [TODO] Save the world
```

The settings "Use Brackets Around Todo Tags" does not seem to affect this.

**Comment by MattFlower** [comment]
Thanks for the report, I'll get a fix out in the next release.

**Comment by MattFlower** [comment]
Sorry, one more release until this gets out.

**Comment by MattFlower** [comment]
Fixed in 0.7.1
