### ISSUE TITLE
Zim to Organized

### ISSUE THREAD

**Issue by davidpgil** [MattFlower/organized#18]
Hi. I am a Zim user and heard about Org-Mode for Emacs. I started learning Emacs and the learning curve is quite steep. So its a big discouraging. I use Atom at work and I found your plugin and it seems like a good idea. I would love to move from Zim to Organized (on Atom) but I am not sure if I cam using Organized as intended. Is there a simple "Getting Started" paragraph I can get? I don't have the context of actually having used Org-Mode before. I just saw videos about it. Would be cool if you can help us with this. Thanks.

**Comment by rbenson** [comment]
Did you look at the samples directory?

**Comment by davidpgil** [comment]
I looked just now and it doesn't seem to make sense to me. For example, how do I make it so the plugin knows that I am in a "notebook" of pages of notes? I look at the side bar on the right and its empty for me. What should I expect to see?

**Comment by rbenson** [comment]
The point of OrgMode is a flat file, and you jump around in that. In the Emacs version, you can tell emacs what org files talk to each other. I don't think @MattFlower implemented that here. Zim, from what I can tell (not a user), works opposite of that.

**Comment by davidpgil** [comment]
This is why I need a primer on how to look at using this.

**Comment by rbenson** [comment]
Other than what's in the ReadMe and [the basics section](https://github.com/MattFlower/organized#learning-the-basics-of-organized), what do you feel like is missing?

**Comment by davidpgil** [comment]
From what I see. The basics just describe what is essentially markdown rules. Why not just use markdown and never use organized? Its unclear for someone who has never used org-mode on emacs.

**Comment by rbenson** [comment]
In emacs, orgmode is 100% more powerful than markdown. As is, organized is not too much different than md, but todo tracking in the sidebar is quite an improvement - though I can't get it to work

**Comment by davidpgil** [comment]
Ah alright. Maybe I will just go back to learning Emacs again. Thanks for helping out.

**Comment by MattFlower** [comment]
@davidpgil The README file and the samples are your best guides at this point.  Sorry it didn't work out for you!
