### ISSUE TITLE
TODO organized sidebar is not working with latest version

### ISSUE THREAD

**Issue by tej27** [MattFlower/organized#23]
TODO organized sidebar is not working with latest version of atom ( 1.21.0 x64). Any help or guidance is highly appreciated.
![capture](https://user-images.githubusercontent.com/17908320/31499967-37674644-af34-11e7-8e93-ae6247530098.JPG)

**Comment by MattFlower** [comment]
When you say it isn’t working, did it work before now or are you a new user?

**Comment by nobleach** [comment]
I can't speak for the issue reporter, but I installed it last week for Atom version 1.21.0, and I'm experiencing the same thing. I haven't tried it with any other release though. When toggling the sidebar, I do not see any errors in the console.

**Comment by MattFlower** [comment]
@nobleach when you were using the sidebar, had you opened a directory with atom?  Or had you set a search path?  

I think I may have spotted the bug. Currently I rely on those two settings to know where to look for TODOs.  For some reason, it never occurred to me before this moment to also check all open tabs. 

If you open a directory or set the search path in config, does it make any difference?

**Comment by nobleach** [comment]
I had opened Atom from a CLI with `atom .`. Let me try opening a directory.

**Comment by nobleach** [comment]
Indeed you are correct. I have an `*.org` file on my Desktop, when opening that folder, toggling the sidebar and hitting refresh, I _can_ see the TODOs.

**Comment by MattFlower** [comment]
This should be fixed in 0.8.0.  I've changed the code to always parse the currently open file, regardless of the folder it resides in.  Let me know if you see any more trouble.

**Comment by nobleach** [comment]
Hey thanks for looking at it!
