### ISSUE TITLE
Sidebar?

### ISSUE THREAD

**Issue by math0ne** [MattFlower/organized#30]
I can't seem to access the sidebar, is it supposed to appear in this menu?

![2017-11-06_22-21-20](https://user-images.githubusercontent.com/3026/32479909-ed56da58-c340-11e7-9370-4db789086660.png)

**Comment by fohria** [comment]
I think you need to go to the "Packages" top menu, there you'll find Organized and then show/hide the sidebar

**Comment by math0ne** [comment]
Yup thats it. Thanks!
