### ISSUE TITLE
Agenda items displays the item above instead of itself

### ISSUE THREAD

**Issue by fohria** [MattFlower/organized#31]
I'm on Atom 1.21.2 on macOS 10.13.1 and organized 0.8.1, using One Dark theme.

Agenda items don't show properly for me. If I do the following, nothing shows on the agenda:

```
# presenting
- SCHEDULED: <2017-11-15 Wed 13:00> [TODO] try out this organizer thingie
    - [TODO] first item
    - [TODO] another item
    - third item
```

And if I do this, the agenda will show the "try out this organizer thingie" item:

```
# presenting
- [TODO] try out this organizer thingie
    - SCHEDULED: <2017-11-15 Wed 13:00> [TODO] first item
    - [TODO] another item
    - third item
```

And so it goes on; if I move the SCHEDULED part down to "another item", the "first item" will be shown in the agenda. Same for third item so doesn't seem to have anything to do with the TODO tag.

On this note, as it may be related, if I have two SCHEDULED tags, like so:

```
# presenting
- [TODO] try out this organizer thingie
    - SCHEDULED: <2017-11-15 Wed 13:00> [TODO] first item
    - SCHEDULED: <2017-11-15 Wed 15:00> [TODO] another item
    - third item
```

It will look like this:

<img width="418" alt="screen shot 2017-11-07 at 18 48 56" src="https://user-images.githubusercontent.com/8695061/32511694-6d9c8360-c3ec-11e7-8461-4d0392cc0541.png">

It's the same in all these cases if I use stars instead of dashes.

Thanks for working on this organizer by the way, found the package today and it's exactly what I need!

**Comment by fohria** [comment]
Just discovered that I probably did not understand the proper syntax, it works if I do this:

```
# presenting
- [TODO] try out this organizer thingie
    SCHEDULED: <2017-11-15 Wed 13:00>
    - [TODO] first item
    SCHEDULED: <2017-11-15 Wed 15:00>
    - [TODO] another item
```

So I guess this is likely not a bug, but related to #22, sorry for polluting your issues! :)

**Comment by MattFlower** [comment]
Indeed, definitely related to #22.  Happy it's working better for you.  -m
