### ISSUE TITLE
Sidebar not working

### ISSUE THREAD

**Issue by triplem** [MattFlower/organized#4]
The sidebar is shown but it stays empty.

**Comment by MattFlower** [comment]
Can you check your settings for organized.  Specifically I want to see if "Settings -> Enabled Toolbar Support" is checked.  If not, that would explain it.  

Other than that setting, I haven't been able to reproduce this.

**Comment by triplem** [comment]
Sure, the setting is Enabled. 

![settings](https://cloud.githubusercontent.com/assets/160079/20708089/a481c740-b62e-11e6-9d44-7f0ebdc74a4c.png)

But the sidebar is still empty:

![files](https://cloud.githubusercontent.com/assets/160079/20708094/af05bfe6-b62e-11e6-96ff-aab4525d1b58.png)

**Comment by seanodell** [comment]
Same. My sidebar is not picking up any [TODO] items I've added.

**Comment by li-bin-bin** [comment]
The same for me.
But, after I installed [tool-bar](https://atom.io/packages/tool-bar) package sidebar becomes active and now I can see all TODOs.

**Comment by gibboni** [comment]
Same problem here. Sidebar stays empty no matter what I do. Clicking the refresh button does not do anything. I have tested this on Windows 7 with Atom 1.13.0. Toolbar works ok. Organized version is 0.5.5 and tool-bar version is 1.0.1

**Comment by Rolograaf** [comment]
Any other suggestion for faultfinding we can do?

**Comment by tyldum** [comment]
I have the same issue. Win 10, Atom 1.16, Organized 0.6.7.

**Comment by bdarcus** [comment]
Same here; doesn't work on either Mint Cinnamon or Fedora 26 (Gnome 3).

**Comment by maddylliieeee** [comment]
I have the same on Win10 Enterprise with Atom 1.16.0 and tool-bar installed + option enabled.

**Comment by nL1ght5** [comment]
Same issue here on Arch Linux
Atom 1.17.0
Organized 0.6.7

**Comment by boileaum** [comment]
Same issue on MacOS 10.12.5
Atom 1.17.2
Organized 0.6.7

**Comment by robitalec** [comment]
I had the same issue on Fedora 25 - my fix was to make sure the folder containing the *.org files was open in the Project pane (with File/Open Folder). After that, the Todo items and Agenda auto-filled as expected.

**Comment by MattFlower** [comment]
Thanks for your patience everybody.  I believe that I have finally solved this error.  If you try version 0.6.8 and still see this error, please comment on this ticket.

**Comment by gibboni** [comment]
Latest version, 0.7.1 on Windows 10.
TODOs are still not showing in the sidebar. Only agenda works. But, that works only with a predefined file. A predefined directory does not do a thing. Also, the "include project paths in search" setting does not do anything.
