### ISSUE TITLE
[Feature Request] VS code version of organized

### ISSUE THREAD

**Issue by senpl** [MattFlower/organized#43]
Is there are known version of this extension to Visual Studio Code. Is there are plans to make one? Would it be hard?

**Comment by MattFlower** [comment]
There are definitely some challenges to do it correctly. When I started work on this plugin I hadn’t really worked with atom plugins, coffeescript, or editor plugins before. I was mostly scratching an itch and publishing what was working for me. Consequently the code isn’t remarkably portable.  I’d love to do it again with a fresh eye, but not right now. 

I’ve always enjoyed editors more than any human should, so undoubtedly I’ll be back at some point.  

Your best bet at the moment is to watch https://github.com/vscode-org-mode/vscode-org-mode/. At this point it is missing some things that make it not worthwhile for me (like folding) but you never know how it will develop.
