### ISSUE TITLE
Incorrect indent behavior for multiple stars

### ISSUE THREAD

**Issue by jkamenik** [MattFlower/organized#7]
My PR #6 fixes a regex issue, and in testing that I noticed that Multiple stars ("**") end up realigning themselves back to the staring line.

This is within the documentation however if I hit "tab" then space are added to the front, which is not.  According to the documentation an additional tab should be added.

Source

```
* One
** Two[|]
```

Hit enter and tab

```
* One
** Two
  **
```

But it should be

```
* One
** Two
***
```

**Comment by MattFlower** [comment]
Fixed in 0.5.3
