### ISSUE TITLE
Strange behaviour of task completion using sidebar

### ISSUE THREAD

**Issue by li-bin-bin** [MattFlower/organized#9]
1) Mark task in sidebar ckecked - org file will be changed like this:
Before:
`* [TODO] some important task`
After:
`* [COMPLETED]  [TODO] some important task`
2) Refresh todos using refresh button in this sidebar - completed task becomes unchecked.

And you can mark task done/undone in sidebar as many times as you want and get this code in org file:
`[TODO]  [COMPLETED]  [TODO]  [COMPLETED]  [COMPLETED]  [TODO]  some important task`

Debian 8
Atom 1.12.7

**Comment by li-bin-bin** [comment]
Also, if I write
` * [COMPLETED] [TODO] some important task`
save the org file, and refresh todos in sidebar - nothing happened. This task still looks like not completed one.

**Comment by MattFlower** [comment]
Fixed in 0.5.8 - thanks for the bug report.

**Comment by vkotovv** [comment]
@MattFlower I can still observe this in 0.8.1. After I click several times on the todo in the sidebar (and *before* I save the file and my task disappears), my notes look like this:
```
* [DONE]  [TODO] [TODO] [TODO] [TODO] [TODO] My task
```
